#!/bin/sh

#update-rc.d xrdp defaults
#/etc/init.d/xrdp start
test -f /etc/xrdp/rsakeys.ini || xrdp-keygen xrdp /etc/xrdp/rsakeys.ini
systemctl daemon-reload || true
service xrdp-sesman start
service xrdp start
exit 0
